# Generated by Django 4.1.13 on 2024-05-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
