# Generated by Django 4.1.13 on 2024-05-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='blog_title',
        ),
    ]
